INSERT INTO site_contents (key, nl_text, en_text, updated_by) VALUES
  ('landing_title', 'Geef verlaten fietsen een duidelijke route naar actie.', 'Give abandoned bikes a clear route to action.', 'system'),
  ('landing_description', 'ZwerfFiets zet straatwaarnemingen om in bruikbare gemeentelijke signalen. Meld een fiets binnen een minuut, zonder account.', 'ZwerfFiets turns street-level observations into structured municipal input. Report a bike in about one minute, without creating an account.', 'system'),
  ('landing_problem_title', 'Nederland heeft naar schatting 100.000 zwerfietsen per jaar', 'The Netherlands has an estimated 100,000 abandoned bikes per year', 'system'),
  ('landing_problem_text', 'Verlaten fietsen zijn een groeiend probleem in steden en dorpen. Ze nemen schaarse stallingruimte in beslag, blokkeren voetpaden en geven buurten een verwaarloosd aanzien. Gemeenten besteden jaarlijks miljoenen aan het opruimen, maar missen vaak de informatie om efficiënt te handelen.', 'Abandoned bikes are a growing problem in cities and towns. They take up scarce storage space, block footpaths, and give neighbourhoods a neglected appearance. Municipalities spend millions annually on clearance, yet often lack the data to act efficiently.', 'system'),
  ('landing_solution_title', 'Burgers en gemeente samen, via een meldpunt zonder drempels', 'Citizens and municipalities together, via a frictionless reporting tool', 'system'),
  ('landing_solution_text', 'ZwerfFiets overbrugt de kloof tussen bewoners die overlast ervaren en gemeenten die actie willen ondernemen. Door het meldproces zo laagdrempelig mogelijk te maken, komt de informatie sneller en preciezer bij de juiste afdeling terecht.', 'ZwerfFiets bridges the gap between residents who experience the nuisance and municipalities that want to take action. By making the reporting process as frictionless as possible, the right information reaches the right department faster and more accurately.', 'system'),
  ('landing_features_title', 'Eenvoudig melden, sneller opruimen', 'Report easily, clean up faster', 'system'),
  ('landing_features_desc', 'Ons platform maakt het zo eenvoudig mogelijk om zwerfietsen te melden. Geen app-download, geen registratie — gewoon je browser openen en binnen een minuut is je melding verzonden.', 'Our platform makes reporting abandoned bikes as simple as possible. No app download, no registration — just open your browser and your report is sent within a minute.', 'system'),
  ('about_mission_title', 'Zwerfietsen van straat — samen met bewoners en gemeenten', 'Getting abandoned bikes off the street — together with residents and municipalities', 'system'),
  ('about_mission_p1', 'ZwerfFiets is een open-source platform dat bewoners in staat stelt om verlaten fietsen te melden bij hun gemeente. Geen app-download, geen account — gewoon een browser openen en melden.', 'ZwerfFiets is an open-source platform that enables residents to report abandoned bikes to their municipality. No app download, no account — just open a browser and report.', 'system'),
  ('about_mission_p2', 'Het platform verbindt de straatwaarneming van burgers met de werkvloer van gemeentelijke handhavers. Elke melding bevat een GPS-locatie, foto''s en conditie-tags, zodat medewerkers snel kunnen beoordelen en actie ondernemen.', 'The platform connects citizens'' street-level observations with the operational teams at municipal enforcement departments. Every report contains a GPS location, photos, and condition tags, so staff can assess and act quickly.', 'system'),
  ('privacy_intro_title', 'Uw privacy, onze prioriteit', 'Your privacy, our priority', 'system'),
  ('privacy_intro_text', 'ZwerfFiets is ontworpen met privacy als uitgangspunt. Voor het indienen van een melding zijn geen account of persoonlijke gegevens vereist.', 'ZwerfFiets is designed with privacy as the default. No account or personal information is required to submit a report.', 'system')
ON CONFLICT (key) DO UPDATE SET 
  nl_text = EXCLUDED.nl_text, 
  en_text = EXCLUDED.en_text 
WHERE site_contents.nl_text = '' AND site_contents.en_text = '';
